apiVersion: v1 
kind: Secret 
metadata:
  name: app-secret
  namespace: {{ .Values.namespace }} 
type: {{.Values.secret.type }} 
data:
  MONGO_URI: {{ .Values.secret.data.MONGO_URI | b64enc }}
  JWT_SECRET: {{ .Values.secret.data.JWT_SECRET | b64enc }} 
  
