apiVersion: v1
kind: Service
metadata:
  name: mongodb-exporter
  namespace: dev
  labels:
    app: mongodb-exporter
spec:
  ports:
  - port: 9216
    targetPort: 9216
    name: http
  selector:
    app: mongodb-exporter