apiVersion: v1 
kind: Secret 
metadata:
  name: app-secret
  namespace: dev 
type: Opaque 
data:   
  MONGO_URI: bW9uZ29kYjovL21vbmdvZGI6MjcwMTcvY29tbWVyY2lhbF9hcHA=    
  JWT_SECRET: bXlzZWNyZXQxMjM=  
  
