[http]
	extraHeader = X-Gitaly-Correlation-ID: 9e1f8b7def8ae1b7-MRS
[transfer]
	bundleURI = true
[http "https://gitlab.com"]
	sslCAInfo = /mnt/c/Users/asus/Desktop/Commercial_App/builds/Y_mTrxRBD/0/Houssemfk_25/project1.tmp/CI_SERVER_TLS_CA_FILE
[url "https://gitlab-ci-token:glcbt-6d_dmZwkyHLhZJ62yhhrhvg@gitlab.com/Houssemfk_25/project1.git"]
	insteadOf = https://gitlab.com/Houssemfk_25/project1.git
[url "https://gitlab-ci-token:glcbt-6d_dmZwkyHLhZJ62yhhrhvg@gitlab.com"]
	insteadOf = https://gitlab.com
