namespace:  dev
nodejs:
    labels:
      app: myapp 
      type: backend
    replicas: 1 
    serviceAccountName: nodejs-sa
    securityContext:
      runAsNonRoot: true
      runAsUser: 1000
    service:
      type: ClusterIP
      port: 80

    deploymentName: deployment-app
    ingressNamespace: ingress-nginx

    name: nodejs
    image: commercial-backend:1.0
    imagePullPolicy: IfNotPresent
    port: 5000

    configmapName: app-config
    secretName: app-secret

    resources:
        requests:
          cpu: "200m"
          memory: "128Mi"
        limits:
          cpu: "500m"
          memory: "256Mi"

    containerSecurityContext:
        readOnlyRootFilesystem: true
    livenessProbe:
       path: /health
       initialDelaySeconds: 15
       periodSeconds: 10

    readinessProbe:
      path: /health
      initialDelaySeconds: 5
      periodSeconds: 5
mongodb:
  labels:  
    app: mongodb 
  replicas: 1 
  podSecurityContext:
    runAsNonRoot: true
    runAsUser: 999
    fsGroup: 999

  name: mongodb
  image: mongo:6
  port: 27017 

  pvc:
    name: mongo-pvc
    mountPath: /data/db
    enabled: true
    storage: "5Gi"
    storageClassName: local-storage
  
  capabilities:
    drop:
      - ALL

  livenessProbe:
    initialDelaySeconds: 30
    periodSeconds: 10

  readinessProbe:
    initialDelaySeconds: 10
    periodSeconds: 5
  service: 
    type: ClusterIP
  pv:
    enabled: true
    name: mongo-pv
    storage: "5Gi"
    path: /data/mongo # On utilise hostPath uniquement en local. Dans le cloud, le PersistentVolume est généralement créé automatiquement via un StorageClass, donc on n’a pas besoin de définir le path.
    storageClassName: local-storage

resourceQuota:
  enabled: true
  pods: "10"
  requests:
    cpu: "4"
    memory: "5Gi"
  limits:
    cpu: "10"
    memory: "10Gi"

limitRange:
  enabled: true     # “J’ai utilisé une condition enabled dans Helm pour activer ou désactiver certaines ressources comme ResourceQuota et LimitRange selon l’environnement, ce qui rend mon déploiement flexible et adaptable.”

  min:
    cpu: "100m"
    memory: "128Mi"

  max:
    cpu: "1"
    memory: "512Mi"

  default:
    cpu: "500m"
    memory: "256Mi"

  defaultRequest:
    cpu: "200m"
    memory: "128Mi"

secret: 
  type: Opaque 
  data:   
    MONGO_URI: mongodb://mongodb:27017/commercial_app   
    JWT_SECRET: mysecret123 
configmap: 
  data:
    NODE_ENV: "production" 
    APP_NAME: "commercial_app"
    PORT: "5000"
    ADMIN_EMAIL: "adminfkih@gmail.com"

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  cpuUtilization: 70

ingress:
  enabled: true
  host: myappnodejs.com
  serviceName: myapp-service
  servicePort: 80

rbac: 
  rules:
    - apiGroups: [""]         
      resources: ["configmaps"] 
      verbs: ["get"]
  roleName: nodejs-role

serviceAccount:
  enabled: true
  name: nodejs-sa

networkPolicy:
  enabled: true

