[http]
	extraHeader = X-Gitaly-Correlation-ID: 9e21c75d7e43e1d9-MRS
[transfer]
	bundleURI = true
[http "https://gitlab.com"]
	sslCAInfo = /mnt/c/Users/asus/Desktop/Commercial_App/builds/kiwW_6a9Y/0/Houssemfk_25/project1.tmp/CI_SERVER_TLS_CA_FILE
[url "https://gitlab-ci-token:glcbt-6d_aFGUkUo4S9kdvsZpx_y8@gitlab.com/Houssemfk_25/project1.git"]
	insteadOf = https://gitlab.com/Houssemfk_25/project1.git
[url "https://gitlab-ci-token:glcbt-6d_aFGUkUo4S9kdvsZpx_y8@gitlab.com"]
	insteadOf = https://gitlab.com
